(defproject uberclj "1.4.0-beta1-20120212"
  :description "Builds an uberjar for Clojure + Clojure-contrib"
  :dependencies [[org.clojure/clojurescript "0.0-971"]
                 [org.clojure/pom.contrib "0.0.25"]
                 [org.clojure/pom.baseline "0.0.19"]
                 [org.clojure/google-closure-library "0.0-790"]
                 [org.clojure/pom.oss-deploy "0.0.19"]
                 [org.clojure/tools.nrepl "0.2.0-beta2"]
                 [org.clojure/data.csv "0.1.1"]
                 [org.clojure/tools.namespace "0.1.2"]
                 [org.clojure/core.unify "0.5.2"]
                 [org.clojure/core.match "0.2.0-alpha9"]
                 [org.clojure/test.generative "0.1.4"]
                 [org.clojure/core.memoize "0.5.1"]
                 [org.clojure/core.cache "0.5.0"]
                 [org.clojure/core.logic "0.6.7"]
                 [org.clojure/algo.generic "0.1.0"]
                 [org.clojure/tools.cli "0.2.1"]
                 [org.clojure/java.jdbc "0.1.1"]
                 [org.clojure/math.combinatorics "0.0.2"]
                 [org.clojure/data.codec "0.1.0"]
                 [org.clojure/math.numeric-tower "0.0.1"]
                 [org.clojure/data.json "0.1.2"]
                 [org.clojure/tools.trace "0.7.1"]
                 [org.clojure/tools.logging "0.2.3"]
                 [org.clojure/data.priority-map "0.0.1"]
                 [org.clojure/java.classpath "0.2.0"]
                 [org.clojure/data.zip "0.1.0"]
                 [org.clojure/algo.monads "0.1.0"]
                 [org.clojure/tools.macro "0.1.1"]
                 [org.clojure/core.incubator "0.1.0"]
                 [org.clojure/java.jmx "0.1"]
                 [org.clojure/data.finger-tree "0.0.1"]
                 [org.clojure/clojure "1.4.0-beta1"]])

